# ==================== [服务基础配置] ====================
server:
  port: 10002
  servlet:
    context-path: /system  # 统一上下文路径
spring:
  application:
    name: system
#  config:
#    import: nacos:application.yaml
    # 从 Nacos 加载 auth.yaml 配置文件
    # 这里只写data ID，其他由下边的config获取；实际开发都推荐 optional: 前缀，防止 Nacos 掉线影响本地启动。
  config:
    import: optional:nacos:system.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.182.131:8848  # 服务注册地址
        # 不写 group，默认就是 DEFAULT_GROU
        namespace: 028ef566-8810-487a-8c5d-9fbc8717ba63  # wabc命名空间id, 环境隔离
      config:
        server-addr: 192.168.182.131:8848
        namespace: 028ef566-8810-487a-8c5d-9fbc8717ba63 # wabc命名空间id, 环境隔离
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true  # 启用动态刷新

# ================= 数据源配置(rbac用户/权限/菜单等) ========================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.131:3306/2025wabc?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: dev123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
# ================= Redis缓存配置(权限表缓存等) ============================
  redis:
    host: 192.168.182.131
    password: dev123
    database: 1  # 使用独立数据库存储令牌
    timeout: 7200

# ================= 安全配置 ============================
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://auth:9001  # OIDC颁发者地址
        jwk-set-uri: ${security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks  # JWK端点

# ================= Mybatis-Plus 配置用以支持代码生成器 ====================
# 不需要
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  type-aliases-package: com.wabc.system.entity
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-field: deleted
#      logic-delete-value: 1
#      logic-not-delete-value: 0

# ================= knife4j/doc接口文档 ============================
knife4j:
  enable: true
  setting:
    language: zh-CN  # 语言设置为中文

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha  # 按字母排序
  openapi:
    info:
      title: "系统管理RBAC API"
      description: "组织/用户/权限"
      version: "1.0"
  group-configs: # 接口分组
    - group: 'system'
      paths-to-match: /system/**
# ================= 日志输出 =============================
logging:
  config: classpath:logback-spring.xml
  level:
    com.wabc: debug
    org.springframework.security: debug  # 调试模式下开启Security详细日志
    com.alibaba.nacos: debug
    org.springframework.cloud.alibaba.nacos: debug
    org.springframework.cloud: debug
service:
  internal:
    access-key: WrY_i6l_-x-t0tM1R3x4jA
    secret-key: X_fI-S0yo7CM7nDaJNxydWagHKhzLEDFC7noquIm8N4